# Generated by Django 5.0.4 on 2024-04-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='resume',
            new_name='subtitle',
        ),
    ]
